### ISSUE TITLE
Fix type errors flagged by ASAN

### ISSUE THREAD

**Issue by simonge** [eic/EICrecon#1476]
There are a few instances flagged up in runtime of values being changed when converted between unsigned/signed or types which aren't large enough when built and run with the debugging environment on github.

At best this just clutters up the trace so it's harder to identify the actual issues, at worst it is effecting the output and isn't being directly flagged by the compiler.

### Environment: (where does this bug occur, have you tried other environments)
The CI environment and build on github.

### Steps to reproduce: (give a step by step account of how to trigger the bug)
1. Run a workflow on github or compiled with the correct settings.

### Expected Result: (what do you expect when you execute the steps above)
No type errors are flagged up

### Actual Result: (what do you get when you execute the steps above)
Several conversions between types which change the value of the variable are flagged up including:

- [ ] `Error: /opt/local/include/eigen3/Eigen/src/Core/arch/SSE/PacketMath.h:608:57: runtime error: implicit conversion from type 'unsigned int' of value 4294967295 (32-bit, unsigned) to type 'int' changed the value to -1 (32-bit, signed)`
From - 
`#15 0x7ffb2af91900 in eicrecon::CKFTrackingFunctionImpl::operator()(Acts::GenericBoundTrackParameters<Acts::ParticleHypothesis> const&, Acts::CombinatorialKalmanFilterOptions<Acts::SourceLinkAdapterIterator<boost::container::vec_iterator<ActsExamples::IndexSourceLink*, true>>, Acts::VectorMultiTrajectory> const&, Acts::TrackContainer<Acts::VectorTrackContainer, Acts::VectorMultiTrajectory, std::shared_ptr>&) const /home/runner/work/EICrecon/EICrecon/src/algorithms/tracking/CKFTrackingFunction.cc:62:26`

- [ ] `/opt/local/include/Acts/TrackFinding/CombinatorialKalmanFilter.hpp:1080:71: runtime error: implicit conversion from type 'std::size_t' (aka 'unsigned long') of value 18446744073709551615 (64-bit, unsigned) to type 'IndexType' (aka 'unsigned int') changed the value to 4294967295 (32-bit, unsigned)`

- [ ] `Error: /opt/local/include/eigen3/Eigen/src/Core/arch/SSE/PacketMath.h:608:57: runtime error: implicit conversion from type 'unsigned int' of value 4294967295 (32-bit, unsigned) to type 'int' changed the value to -1 (32-bit, signed)`
From - 
`#33 0x7ffb2b06e4cf in eicrecon::IterativeVertexFinder::produce(std::vector<ActsExamples::Trajectories const*, std::allocator<ActsExamples::Trajectories const*>>) /home/runner/work/EICrecon/EICrecon/src/algorithms/tracking/IterativeVertexFinder.cc:114:24`

- [ ] `/opt/local/include/boost/iostreams/filter/gzip.hpp:479:33: runtime error: implicit conversion from type 'int' of value 139 (32-bit, signed) to type 'char' changed the value to -117 (8-bit, signed)`
From -
`#7 0x7ffb2c2fdfbf in eicrecon::PIDLookupTable::load_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, eicrecon::PIDLookupTable::Binning const&) /home/runner/work/EICrecon/EICrecon/src/services/pid_lut/PIDLookupTable.cc:83:12`

- [ ] `Error: /opt/local/include/eigen3/Eigen/src/Core/arch/SSE/PacketMath.h:608:57: runtime error: implicit conversion from type 'unsigned int' of value 4294967295 (32-bit, unsigned) to type 'int' changed the value to -1 (32-bit, signed)`
From - 
`#8 0x7ffb11500c8b in eicrecon::ImagingClusterReco::fit_track(std::vector<edm4eic::MutableCluster, std::allocator<edm4eic::MutableCluster>> const&) const /home/runner/work/EICrecon/EICrecon/src/algorithms/calorimetry/ImagingClusterReco.h:300:44`

- [ ] `Error: /home/runner/work/EICrecon/EICrecon/src/algorithms/fardetectors/FarDetectorTrackerCluster.cc:89:20: runtime error: implicit conversion from type 'std::uint64_t' (aka 'unsigned long') of value 18228604664725636550 (64-bit, unsigned) to type 'const long' changed the value to -218139408983915066 (64-bit, signed)`

- [ ] `/opt/local/include/edm4hep/ObjectID.h:26:71: runtime error: implicit conversion from type 'uint32_t' (aka 'unsigned int') of value 3167178110 (32-bit, unsigned) to type 'std::int32_t' (aka 'int') changed the value to -1127789186 (32-bit, signed)` 
From - 
`#1 0x7ffb0e7d6ef4 in eicrecon::FarDetectorTrackerCluster::ConvertClusters(std::vector<FDTrackerCluster, std::allocator<FDTrackerCluster>> const&, edm4hep::TrackerHitCollection&) const /home/runner/work/EICrecon/EICrecon/src/algorithms/fardetectors/FarDetectorTrackerCluster.cc:198:29`

**Comment by wdconinc** [comment]
Some of these have been fixed by #1582 #1547
