### ISSUE TITLE
Division by zero in CalorimeterClusterRecoCoG

### ISSUE THREAD

**Issue by wdconinc** [eic/EICrecon#1583]
### Environment: (where does this bug occur, have you tried other environments)
- Which branch (often `main` for latest released): topocluster-sort (might be specific to branch)
- Which version (or `HEAD` for the most recent on git):
- Any specific OS or system where the issue occurs?
- Any special versions of ROOT or Geant4?

### Steps to reproduce: (give a step by step account of how to trigger the bug)
1. https://github.com/eic/EICrecon/actions/runs/10446101104/job/28923156561#step:8:6332

### Expected Result: (what do you expect when you execute the steps above)
No division by zero.

### Actual Result: (what do you get when you execute the steps above)
```
Error: /home/runner/work/EICrecon/EICrecon/src/algorithms/calorimetry/CalorimeterClusterRecoCoG.h:34:43: runtime error: division by zero
/usr/bin/llvm-symbolizer-16: /opt/local/lib/libcurl.so.4: no version information available (required by /usr/bin/llvm-symbolizer-16)
    #0 0x7f3b771794dc in logWeight(double, double, double, int) /home/runner/work/EICrecon/EICrecon/src/algorithms/calorimetry/CalorimeterClusterRecoCoG.h:34:43
    #1 0x7f3b7717d8ad in std::function<double (double, double, double, int)>::operator()(double, double, double, int) const /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/std_function.h:591:9
    #2 0x7f3b7717d8ad in eicrecon::CalorimeterClusterRecoCoG::reconstruct(edm4eic::ProtoCluster const&) const /home/runner/work/EICrecon/EICrecon/src/algorithms/calorimetry/CalorimeterClusterRecoCoG.cc:204:25
    #3 0x7f3b7717a466 in eicrecon::CalorimeterClusterRecoCoG::process(std::tuple<gsl::not_null<edm4eic::ProtoClusterCollection const*>, edm4hep::SimCalorimeterHitCollection const*> const&, std::tuple<gsl::not_null<edm4eic::ClusterCollection*>, edm4eic::MCRecoClusterParticleAssociationCollection*> const&) const /home/runner/work/EICrecon/EICrecon/src/algorithms/calorimetry/CalorimeterClusterRecoCoG.cc:71:21
    #4 0x7f3b77621f09 in eicrecon::CalorimeterClusterRecoCoG_factory::Process(long, unsigned long) /home/runner/work/EICrecon/EICrecon/src/factories/calorimetry/CalorimeterClusterRecoCoG_factory.h:49:17
```

**Comment by wdconinc** [comment]
Also in main. https://github.com/eic/EICrecon/actions/runs/10449772535/job/28932927472#step:8:6334
